name: Test

on:
  push:
jobs:
  test-agent-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        env:
          AGENT_TOOLSDIRECTORY: '/tmp/toolpath'
        uses: techman83/setup-python@fix/tool_path
        with:
          python-version: "3.11.0-beta.4"
          cache: pip
      - name: Python Version
        run: python --version
